version: '3.4'
services:
  netbox: &netbox
    image: vaporio/netbox:develop
    build:
      context: .
      args:
        BUILD_VERSION: 'local-dev'
        BUILD_DATE: ''
        VCS_REF: 'tip'
    depends_on:
    - postgres
    - redis
    - redis-cache
    - netbox-worker
    env_file: docker/env/netbox.env
    #user: '1000:1000'
    volumes:
    - ./netbox:/opt/netbox/netbox
    - ./docker/startup_scripts:/opt/netbox/startup_scripts:z,ro
    - ./docker/initializers:/opt/netbox/initializers:z,ro
    - ./docker/configuration:/etc/netbox/config:z,ro
    - ./reports:/etc/netbox/reports:z,ro
    - ./scripts:/etc/netbox/scripts:z,ro
    - netbox-nginx-config:/etc/netbox-nginx:z
    - netbox-static-files:/opt/netbox/netbox/static:z
    - netbox-media-files:/opt/netbox/netbox/media:z
  netbox-worker:
    <<: *netbox
    depends_on:
    - redis
    entrypoint:
    - python3
    - /opt/netbox/netbox/manage.py
    command:
    - rqworker
  nginx:
    command: nginx -c /etc/netbox-nginx/nginx.conf
    image: nginx:1.18
    depends_on:
    - netbox
    ports:
    - 8000:8080
    volumes:
    - netbox-static-files:/opt/netbox/netbox/static:ro
    - netbox-nginx-config:/etc/netbox-nginx/:ro
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: netbox
    volumes:
    - netbox-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:5-alpine
    volumes:
    - netbox-redis-data:/data
  redis-cache:
    image: redis:5-alpine
volumes:
  netbox-static-files:
    driver: local
  netbox-nginx-config:
    driver: local
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-data:
    driver: local
