sf_id:
  type: text
  label: Salesforce ID
  description: Salesforce Record ID
  required: false
  weight: 0
  filter_logic: exact
  on_objects:
  - dcim.models.Site
  - dcim.models.Region
  - dcim.models.Device
